program: sweep.py
method: grid
metric:
  goal: minimize
  name: valid_frame_mae_epoch
parameters:
  lambda:
    values: [0, 1e-11, 1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2]
  num_epoch_lambda:
    values: [5, 10, 20]